# Generated by Django 5.2 on 2025-06-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEscuela1', '0003_alter_estudiante_email_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='profesion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
