# Generated by Django 5.2 on 2025-06-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEscuela1', '0004_avatar_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='AppEscuela1/img/avatar_default.png', null=True, upload_to='avatares'),
        ),
    ]
