# Generated by Django 5.2 on 2025-06-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEscuela1', '0005_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
